### ISSUE TITLE
Read timeout

### ISSUE THREAD

**Issue by thezim** [jenkinsci/fortify-plugin#11]
We are receiving read timeout errors when during the upload step. The strange part is that on the SSC server the FPR upload is successfully and it is processed correctly once there. Note that this only occurs for larger FPRs with more issues.

```Error uploading to SSC: https://redactedhostname/ssc
com.fortify.ssc.restclient.ApiException: java.net.SocketTimeoutException: Read timed out
	at com.fortify.ssc.restclient.ApiClient.execute(ApiClient.java:846)
	at com.fortify.ssc.restclient.api.ArtifactOfProjectVersionControllerApi.uploadArtifactOfProjectVersionWithHttpInfo(ArtifactOfProjectVersionControllerApi.java:314)
	at com.fortify.ssc.restclient.api.ArtifactOfProjectVersionControllerApi.uploadArtifactOfProjectVersion(ArtifactOfProjectVersionControllerApi.java:298)
	at com.fortify.plugin.jenkins.fortifyclient.ApiClientWrapper.uploadFpr(ApiClientWrapper.java:498)
	at com.fortify.plugin.jenkins.fortifyclient.FortifyClient.uploadFPR(FortifyClient.java:155)
	at com.fortify.plugin.jenkins.steps.FortifyUpload$1.runWith(FortifyUpload.java:271)
	at com.fortify.plugin.jenkins.steps.FortifyUpload$1.runWith(FortifyUpload.java:268)
	at com.fortify.plugin.jenkins.steps.FortifyUpload.runWithFortifyClient(FortifyUpload.java:788)
	at com.fortify.plugin.jenkins.steps.FortifyUpload.uploadToSSC(FortifyUpload.java:267)
	at com.fortify.plugin.jenkins.steps.FortifyUpload.perform(FortifyUpload.java:194)
	at com.fortify.plugin.jenkins.steps.FortifyUpload$Execution.run(FortifyUpload.java:809)
	at com.fortify.plugin.jenkins.steps.FortifyUpload$Execution.run(FortifyUpload.java:798)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
	at com.squareup.okhttp.Call.getResponse(Call.java:287)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at com.fortify.ssc.restclient.ApiClient.execute(ApiClient.java:842)
```

**Comment by thezim** [comment]
Okay here is the deal. `fortify-plugin` uses [ssc-restapi-client](https://github.com/fortify/ssc-restapi-client) which in turn uses [okhttp](https://github.com/square/okhttp). `okhttp` [default read timeout](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/read-timeout/) is 10s and neither `fortify-plugin` or `ssc-restapi-client` has functionality to pass timeouts down the call stack to `okhttp`.

As a proof I [modified](https://github.com/thezim/ssc-restapi-client) `ssc-restapi-client` with at hard coded timeout set and injected the new jar in to the plugin and it now works.

This plugin should support passing of timeouts for the web calls (`ssc-restapi-client` too) as 10s simply isn't enough time especially across the internet or large FPRs.

**Comment by tvanhill** [comment]
I am encountering the same issue uploading an ~25 MB file. 

I took a look at the proposed PR (https://github.com/fortify/ssc-restapi-client/pull/4) for ssc-restapi-client and believe this should be fixed directly in the Fortify Jenkins plugin. I modified  the com.fortify.plugin/jenkins/fortify.client.ApiClientWrapper class's constructor to specify connect and read timeouts by calling the following methods:
* ApiClient.setConnectTimeout(connectTimeout)
* ApiClient.setConnectTimeout(readTimeout)

I also modified the the plugin so that these values could be specified via pipeline. The modified code is attached and i have verified that the input values is used and that setting a larger value solves this problem.

[fortifyjenkins.zip](https://github.com/jenkinsci/fortify-plugin/files/4530403/fortifyjenkins.zip)

**Comment by thezim** [comment]
@tvanhill Do you have a PR for this yet?

**Comment by tvanhill** [comment]
I  did not open pull request as I saw the pull request linked below. I attached the updated source to that pull request and the author was going to test with it.

https://github.com/jenkinsci/fortify-plugin/pull/14

**Comment by tiversusit** [comment]
I'm running into this issue when first trying to configure the plugin.  Connection fails after about 10 seconds.  

**Cannot connect to SSC server

java.net.SocketTimeoutException: Read timed out

	at java.net.SocketInputStream.socketRead0(Native Method)

	at java.net.SocketInputStream.socketRead(Unknown Source)

	at java.net.SocketInputStream.read(Unknown Source)

	at java.net.SocketInputStream.read(Unknown Source)

	at sun.security.ssl.InputRecord.readFully(Unknown Source)

	at sun.security.ssl.InputRecord.read(Unknown Source)

	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)

	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)

	at sun.security.ssl.AppInputStream.read(Unknown Source)

	at okio.Okio$2.read(Okio.java:139)

	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)

Caused: java.net.SocketTimeoutException: timeout

	at okio.Okio$3.newTimeoutException(Okio.java:207)

	at okio.AsyncTimeout.exit(AsyncTimeout.java:261)

	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)

	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)

	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)

	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)

	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)

	at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)

	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)

	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)

	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)

	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)

	at com.squareup.okhttp.Call.getResponse(Call.java:287)

	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)

	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)

	at com.squareup.okhttp.Call.execute(Call.java:80)

	at com.fortify.ssc.restclient.ApiClient.execute(ApiClient.java:842)

Caused: com.fortify.ssc.restclient.ApiException

	at com.fortify.ssc.restclient.ApiClient.execute(ApiClient.java:846)

	at com.fortify.ssc.restclient.api.ProjectVersionControllerApi.listProjectVersionWithHttpInfo(ProjectVersionControllerApi.java:1060)

	at com.fortify.ssc.restclient.api.ProjectVersionControllerApi.listProjectVersion(ProjectVersionControllerApi.java:1038)

	at com.fortify.plugin.jenkins.fortifyclient.ApiClientWrapper.getApplicationVersions(ApiClientWrapper.java:116)

	at com.fortify.plugin.jenkins.fortifyclient.FortifyClient.getProjectListEx(FortifyClient.java:98)

	at com.fortify.plugin.jenkins.fortifyclient.FortifyClient.getProjectList(FortifyClient.java:80)

	at com.fortify.plugin.jenkins.FortifyPlugin$DescriptorImpl$1.runWith(FortifyPlugin.java:1104)

	at com.fortify.plugin.jenkins.FortifyPlugin$DescriptorImpl$1.runWith(FortifyPlugin.java:1100)

	at com.fortify.plugin.jenkins.FortifyPlugin.runWithFortifyClient(FortifyPlugin.java:835)

	at com.fortify.plugin.jenkins.FortifyPlugin.access$100(FortifyPlugin.java:86)

	at com.fortify.plugin.jenkins.FortifyPlugin$DescriptorImpl.doTestConnection(FortifyPlugin.java:1100)

	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)

	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)

	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)

	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)

	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)

	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)

	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)

	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)

	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)

	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:280)

	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)

	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)

	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)

	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:676)

	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)

	at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:76)

	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)

	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)

	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)

	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:153)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)

	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)

	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)

	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)

	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)

	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)

	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)

	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)

	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)

	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)

	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:36)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)

	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)

	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:643)

	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)

	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)

	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)

	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)

	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)

	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)

	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)

	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)

	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)

	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

	at java.lang.Thread.run(Unknown Source)**
